#!/usr/bin/env python3
"""Generate js/weights/w_XX.js — embed model weights as plain JS code.

The whole minimind-3/model.safetensors binary is base64-encoded, split into
fixed-size chunks and emitted as classic scripts, each appending to
window.__MM_B64. config.json and tokenizer.json are embedded as JS objects.
This makes the page fully standalone: double-click index.html, zero dialogs.

Usage: python3 tools/gen_weights_js.py [--chunk-chars 12000000]
"""
import argparse, base64, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = os.path.join(ROOT, "minimind-3")
OUT_DIR = os.path.join(ROOT, "js", "weights")
INDEX = os.path.join(ROOT, "index.html")

BEGIN = "<!-- WEIGHTS:BEGIN (generated by tools/gen_weights_js.py) -->"
END = "<!-- WEIGHTS:END -->"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chunk-chars", type=int, default=12_000_000,
                    help="base64 chars per generated JS file (multiple of 4)")
    args = ap.parse_args()
    assert args.chunk_chars % 4 == 0, "chunk must be multiple of 4"

    src = os.path.join(MODEL, "model.safetensors")
    size = os.path.getsize(src)
    print(f"reading {src} ({size/1048576:.1f} MB)…")
    with open(src, "rb") as f:
        raw = f.read()
    b64 = base64.b64encode(raw).decode("ascii")
    del raw
    print(f"base64 length: {len(b64)/1048576:.1f} M chars")

    os.makedirs(OUT_DIR, exist_ok=True)
    # clear previous parts
    for old in os.listdir(OUT_DIR):
        if old.startswith("w_") and old.endswith(".js"):
            os.remove(os.path.join(OUT_DIR, old))

    n_parts = (len(b64) + args.chunk_chars - 1) // args.chunk_chars
    tags = []
    for i in range(n_parts):
        chunk = b64[i*args.chunk_chars:(i+1)*args.chunk_chars]
        body = (
            "/* AUTO-GENERATED weight data chunk %02d/%02d - do not edit. */\n"
            "window.__MM_B64 = window.__MM_B64 || [];\n"
            "window.__MM_B64.push(\"%s\");\n" % (i, n_parts, chunk)
        )
        name = f"w_{i:02d}.js"
        with open(os.path.join(OUT_DIR, name), "w", encoding="ascii") as f:
            f.write(body)
        tags.append(f'<script src="js/weights/{name}"></script>')
        print(f"  wrote {name} ({len(chunk)/1048576:.1f} MB chars)")

    # small configs embedded as JS objects
    cfg = json.load(open(os.path.join(MODEL, "config.json"), encoding="utf-8"))
    with open(os.path.join(OUT_DIR, "config.js"), "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED — model config embedded */\n")
        f.write("window.__MM_CONFIG = ")
        f.write(json.dumps(cfg, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    tags.append('<script src="js/weights/config.js"></script>')

    tj_path = os.path.join(MODEL, "tokenizer.json")
    with open(tj_path, "r", encoding="utf-8") as f:
        tj_raw = f.read()
    json.loads(tj_raw)  # validate
    with open(os.path.join(OUT_DIR, "tokenizer.js"), "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED — tokenizer embedded */\n")
        f.write("window.__MM_TOKJSON = ")
        f.write(tj_raw.strip())
        f.write(";\n")
    tags.append('<script src="js/weights/tokenizer.js"></script>')

    # splice script tags into index.html between markers
    html = open(INDEX, encoding="utf-8").read()
    block = BEGIN + "\n" + "\n".join(tags) + "\n" + END
    if BEGIN in html and END in html:
        pre = html[:html.index(BEGIN)]
        post = html[html.index(END) + len(END):]
        html = pre + block + post
    else:
        anchor = '<script src="js/vendor/tf.min.js"></script>'
        assert anchor in html, "anchor not found in index.html"
        html = html.replace(anchor, anchor + "\n" + block, 1)
    open(INDEX, "w", encoding="utf-8").write(html)
    print(f"index.html updated with {len(tags)} weight script tags")
    print("done.")

if __name__ == "__main__":
    main()
