#!/usr/bin/env python3
"""Generate js/weights/ — INT8-native embedded weights (format v2).

Each big matrix is quantized per-output-channel symmetric INT8:
    scale[o] = max|W[o,:]|/127 ;  q = round(W/scale) ∈ [-127,127]
and emitted as one classic script per tensor:
    window.__MM_QPACK.push({name, dIn, dOut, data:"<b64 of int8>", scales:"<b64 of f32>"})
Norm weights stay FP32 and go to misc.js (window.__MM_MISC). config/tokenizer
are embedded as JS objects. Result: ~82MB on disk instead of 164MB, and the
page runs with ~61MB resident weights instead of 244MB.

Usage: python3 tools/gen_weights_int8.py [--src minimind-3/model.safetensors]
(Original FP16 embedding generator: tools/gen_weights_js.py)
"""
import argparse, base64, json, os, struct, sys
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "js", "weights")
INDEX = os.path.join(ROOT, "index.html")
BEGIN = "<!-- WEIGHTS:BEGIN (generated by tools/gen_weights_int8.py) -->"
END = "<!-- WEIGHTS:END -->"

def read_safetensors(path):
    with open(path, "rb") as f:
        n = struct.unpack("<Q", f.read(8))[0]
        hdr = json.loads(f.read(n))
        base = 8 + n
    out = {}
    for name, rec in hdr.items():
        if name == "__metadata__":
            continue
        s, e = rec["data_offsets"]
        dt, shape = rec["dtype"], rec["shape"]
        with open(path, "rb") as f:
            f.seek(base + s)
            raw = f.read(e - s)
        if dt == "F16":
            arr = np.frombuffer(raw, dtype="<f2").astype(np.float32)
        elif dt == "F32":
            arr = np.frombuffer(raw, dtype="<f4")
        elif dt == "BF16":
            arr = (np.frombuffer(raw, dtype="<u2").astype(np.uint32) << 16).view(np.float32)
        else:
            raise ValueError(f"unsupported dtype {dt}")
        out[name] = arr.reshape(shape) if shape else arr
    return out

def q8_per_row(t):
    maxabs = np.max(np.abs(t), axis=1).astype(np.float32)
    scale = np.maximum(maxabs / 127.0, 1e-12).astype(np.float32)
    q = np.clip(np.rint(t / scale[:, None]), -127, 127).astype(np.int8)
    err = np.abs(q.astype(np.float32) * scale[:, None] - t)
    return q, scale, float(err.max())

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=os.path.join(ROOT, "minimind-3", "model.safetensors"))
    args = ap.parse_args()
    print(f"reading {args.src} …")
    tensors = read_safetensors(args.src)

    d, L, inter, V = 768, 8, 2432, 6400
    BIG = {"model.embed_tokens.weight": (V, d)}
    MISC = []
    for l in range(L):
        BIG[f"model.layers.{l}.self_attn.q_proj.weight"] = (8 * 96, d)
        BIG[f"model.layers.{l}.self_attn.k_proj.weight"] = (4 * 96, d)
        BIG[f"model.layers.{l}.self_attn.v_proj.weight"] = (4 * 96, d)
        BIG[f"model.layers.{l}.self_attn.o_proj.weight"] = (d, 8 * 96)
        BIG[f"model.layers.{l}.mlp.gate_proj.weight"] = (inter, d)
        BIG[f"model.layers.{l}.mlp.up_proj.weight"] = (inter, d)
        BIG[f"model.layers.{l}.mlp.down_proj.weight"] = (d, inter)
    for name in tensors:
        if "norm" in name and name not in BIG:
            MISC.append(name)

    os.makedirs(OUT_DIR, exist_ok=True)
    for old in os.listdir(OUT_DIR):
        if old.endswith(".js"):
            os.remove(os.path.join(OUT_DIR, old))

    tags, total_b64, max_err = [], 0, 0.0
    idx = 0
    for name, (dOut, dIn) in BIG.items():
        t = tensors[name]
        q, scale, err = q8_per_row(t)
        max_err = max(max_err, err)
        data_b64 = base64.b64encode(q.tobytes()).decode("ascii")
        sc_b64 = base64.b64encode(scale.tobytes()).decode("ascii")
        total_b64 += len(data_b64) + len(sc_b64)
        fname = f"q_{idx:02d}.js"
        with open(os.path.join(OUT_DIR, fname), "w", encoding="ascii") as f:
            f.write("/* AUTO-GENERATED INT8 quantized weight - do not edit. */\n")
            f.write("window.__MM_QPACK = window.__MM_QPACK || [];\n")
            f.write("window.__MM_QPACK.push({name:%s,dIn:%d,dOut:%d,data:\"%s\",scales:\"%s\"});\n"
                    % (json.dumps(name), dIn, dOut, data_b64, sc_b64))
        tags.append(f'<script src="js/weights/{fname}"></script>')
        idx += 1
        print(f"  {fname}  {name}  [{dOut}x{dIn}]  {len(data_b64)/1048576:.2f} MB(b64)  err={err:.2e}")

    # misc FP32 norm weights
    misc = []
    for name in MISC:
        t = np.ascontiguousarray(tensors[name], dtype=np.float32)
        misc.append({"name": name, "shape": list(t.shape), "b64": base64.b64encode(t.tobytes()).decode("ascii")})
    with open(os.path.join(OUT_DIR, "misc.js"), "w", encoding="ascii") as f:
        f.write("/* AUTO-GENERATED FP32 norm weights - do not edit. */\n")
        f.write("window.__MM_MISC = " + json.dumps(misc, separators=(",", ":")) + ";\n")
    tags.append('<script src="js/weights/misc.js"></script>')
    print(f"  misc.js  {len(misc)} FP32 norm tensors")

    # config + tokenizer
    cfg = json.load(open(os.path.join(ROOT, "minimind-3", "config.json"), encoding="utf-8"))
    with open(os.path.join(OUT_DIR, "config.js"), "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED - model config embedded */\nwindow.__MM_CONFIG = ")
        f.write(json.dumps(cfg, ensure_ascii=False, separators=(",", ":")) + ";\n")
    tags.append('<script src="js/weights/config.js"></script>')
    tj = open(os.path.join(ROOT, "minimind-3", "tokenizer.json"), encoding="utf-8").read()
    json.loads(tj)
    with open(os.path.join(OUT_DIR, "tokenizer.js"), "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED - tokenizer embedded */\nwindow.__MM_TOKJSON = ")
        f.write(tj.strip() + ";\n")
    tags.append('<script src="js/weights/tokenizer.js"></script>')

    # splice tags
    html = open(INDEX, encoding="utf-8").read()
    block = BEGIN + "\n" + "\n".join(tags) + "\n" + END
    if BEGIN in html and END in html:
        html = html[:html.index(BEGIN)] + block + html[html.index(END) + len(END):]
    else:
        anchor = '<script src="js/vendor/tf.min.js"></script>'
        html = html.replace(anchor, anchor + "\n" + block, 1)
    open(INDEX, "w", encoding="utf-8").write(html)

    fp32_mb = sum(int(np.prod(tensors[n].shape)) for n in BIG) * 4 / 1048576
    print(f"\nINT8 embedded: {len(tags)} script tags, b64 total {total_b64/1048576:.1f} MB "
          f"(fp32 equivalent {fp32_mb:.0f} MB, ratio {fp32_mb/(total_b64/1048576):.2f}x vs b64 / 4.0x vs binary)")
    print(f"weight max quantization error: {max_err:.3e}")

if __name__ == "__main__":
    main()
