[system-multimodal]
# 多模态模型配置
model = ./local_data/models/Qwen3.5-9B-UD-Q4_K_XL.gguf
# 多模态模型的 mmproj 模型路径
mmproj = ./local_data/models/mmproj-Qwen3.5-9B-UD-BF16.gguf
# 推测解码类型：使用多令牌预测草稿模型
spec-type = draft-mtp
# 推测解码最大草稿令牌数
spec-draft-n-max = 3
# 不将载入的 mmproj 模型卸载到 GPU
no-mmproj-offload = true

[system-embedding]
# 嵌入模型配置
model = ./local_data/models/Qwen3-Embedding-0.6B-Q8_0.gguf
# 是否启用嵌入模型
embeddings = true
# 嵌入模型的 spec 类型：无
spec-type = none
# 嵌入模型的上下文大小：4096
ctx-size = 4096 
# 嵌入模型的 GPU 层数：0
gpu-layers = 0
# 启用内存锁定
mlock = true
