[system-multimodal]
# 多模态模型配置
model = D:\Chat_AI_Case\lmstudio\models\Lunar\Gemma-4-12B\gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
# 上下文窗口大小：20K tokens
ctx-size = 20480
# 是否启用上下文偏移
context-shift = true
# GPU层数：尽可能多地将层卸载到GPU
# n-gpu-layers = all
# 禁用 mmap 缓存
no-mmap = true
# 推理模式：自动推理模式
reasoning = off
# reasoning-budget = 512
# reasoning-budget-message = "Please stop thinking and give a natural answer directly"
# 多模态模型的 mmproj 模型路径
mmproj = D:\Chat_AI_Case\lmstudio\models\Lunar\Gemma-4-12B\mmproj-BF16.gguf
# 不将载入的 mmproj 模型卸载到 GPU
no-mmproj-offload = true
# 多模态模型的草稿模型路径
model-draft = D:\Chat_AI_Case\lmstudio\models\Lunar\Gemma-4-12B\mtp-gemma-4-12B-it.gguf
# 推测解码类型：使用多令牌预测草稿模型
spec-type = draft-mtp
# 推测解码最大草稿令牌数
spec-draft-n-max = 4
# 草稿模型的 K 缓存数据类型
spec-draft-type-k = q8_0
# 草稿模型的 V 缓存数据类型
spec-draft-type-v = q8_0

[system-embedding]
# 嵌入模型配置
model = ./local_data/models/Qwen3-Embedding-0.6B.gguf
# 是否启用嵌入模型
embeddings = true
# 嵌入模型的 spec 类型：无
spec-type = none
# 嵌入模型的上下文大小
ctx-size = 4096 
# 禁用使用 GPU 加速推理
n-gpu-layers = 0
